artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/udit-rawat/ADL/raw/refs/heads/main/heart_2020_cleaned.csv.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/heart_2020_cleaned.csv
  STATUS_FILE: artifacts/data_validation/status.txt
